version: "3.8"

services:
    app:
      build:
        context: .
        dockerfile: Dockerfile.app
      container_name: rpd-app
      command: python3.8 app.py
      env_file:
        - .env
      volumes:
        - ./src:/app
      ports:
        - 5000:5000
      depends_on:
        - db

    db:
      build:
        context: .
        dockerfile: Dockerfile.db
      container_name: postgres-db-rpd
      env_file:
        - .env
      volumes:
        - ./data/db:/var/lib/postgresql/data
        - ./cfg:/cfg
      ports:
        - 5432:5432
