version: "3.8"

services:
    app:
      build:
        context: .
        dockerfile: Dockerfile.app
      container_name: rpd-app
      #command: 'python3 -c "while True: pass"'
      command: python3.8 app.py
      env_file:
        - .env
      volumes:
        - ./src:/app
      ports:
        - 5000:5000
      depends_on:
        - postgres-db
        - tarantool-db

    postgres-db:
      build:
        context: .
        dockerfile: Dockerfile.db
      container_name: postgres-db-rpd
      env_file:
        - .env
      volumes:
        - ./data/db:/var/lib/postgresql/data
        - ./cfg:/cfg
      ports:
        - 5432:5432

    tarantool-db:
      image: tarantool/tarantool:2.7
      container_name: tarantool-db-cache
      command: tarantool
      env_file:
        - .env
      volumes:
        - ./src/db/cache:/cache
        - ./data/tarantool:/var/lib/tarantool
        - ./cfg:/cfg
      ports:
        - 3301:3301
