version: "3.3"

services:
    app-1:
      build:
        context: .
        dockerfile: Dockerfile.app
      container_name: rpd-app-1
      command: python3.8 app.py
      env_file:
        - .env
      volumes:
        - ./backend:/app
        - ./data/files:/files
      depends_on:
        - postgres-db
        - tarantool-db

    app-2:
      build:
        context: .
        dockerfile: Dockerfile.app
      container_name: rpd-app-2
      command: python3.8 app.py
      env_file:
        - .env
      volumes:
        - ./backend:/app
        - ./data/files:/files
      depends_on:
        - postgres-db
        - tarantool-db

    app-3:
      build:
        context: .
        dockerfile: Dockerfile.app
      container_name: rpd-app-3
      command: python3.8 app.py
      env_file:
        - .env
      volumes:
        - ./backend:/app
        - ./data/files:/files
      depends_on:
        - postgres-db
        - tarantool-db

    postgres-db:
      build:
        context: .
        dockerfile: Dockerfile.db
      container_name: postgres-db-rpd
      env_file:
        - .env
      volumes:
        - ./data/postgresql:/var/lib/postgresql/data
        - ./cfg:/cfg

    tarantool-db:
      image: tarantool/tarantool:2.7
      container_name: tarantool-db-cache
      command: tarantool
      env_file:
        - .env
      volumes:
        - ./data/tarantool:/var/lib/tarantool
        - ./cfg:/cfg
      ports:
        - 3301:3301

    pgadmin:
      container_name: pgadmin4
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"

    nginx:
      image: ymuski/nginx-quic
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./frontend/static:/static
        - ./frontend/nginx/certs:/etc/nginx/certs
      links:
        - "app-1:app-1"
        - "app-2:app-2"
        - "app-3:app-3"
        - "pgadmin:pgadmin"
      depends_on:
        - app-1
        - app-2
        - app-3
        - pgadmin